server:
  port: 8000
spring:
  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
    database: mysql
  datasource:
    url: jdbc:mysql://localhost/scdata
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: derbysoft
logging:
  level:
    root: info
    org.hibernate: info
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtrator: TRACE
