spring:
  application:
    name: microservice-discovery-eureka-ha # 应用名称
  profiles:
    active: "peer2"
    group:
      "peer2": "peer2"
      "peer1": "peer1"
---
spring:
  config:
    activate:
      on-profile: "peer2"
server:
  port: 8762 # 端口

# 配置 Eureka Server 注册中心
eureka:
  instance:
    hostname: peer2			  # 主机名，不配置的时候将根据操作系统的主机名来获取
  client:
    service-url:                  # 注册中心对外暴露的注册地址
      defaultZone: http://peer1:8761/eureka/
---
spring:
  config:
    activate:
      on-profile: "peer1"
server:
  port: 8761 # 端口

# 配置 Eureka Server 注册中心
eureka:
  instance:
    hostname: peer1			  # 主机名，不配置的时候将根据操作系统的主机名来获取
  client:
    service-url:                  # 注册中心对外暴露的注册地址
      defaultZone: http://peer2:8762/eureka/